# Generated by Django 4.2.5 on 2023-10-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
